name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup VS Dev Environment
      uses: microsoft/setup-msbuild@v1.1

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config Release

    - name: Create Release ZIP
      run: |
        cd ${{github.workspace}}/build/Release
        7z a ${{github.workspace}}/ermerchant.zip ermerchant.dll LICENSE.txt ermerchant.ini

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ermerchant.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
